export const START_LOADING_ALL_GROUP_LIST = 'START_LOADING_ALL_GROUP_LIST';
export const SUCCESSFUL_LOADING_ALL_GROUP_LIST = 'SUCCESSFUL_LOADING_ALL_GROUP_LIST';
export const FAILED_LOADING_ALL_GROUP_LIST = 'FAILED_LOADING_ALL_GROUP_LIST';