export const START_LOADING_ALL_USER_LIST = 'START_LOADING_ALL_USER_LIST';
export const SUCCESSFUL_LOADING_ALL_USER_LIST = 'SUCCESSFUL_LOADING_ALL_USER_LIST';
export const FAILED_LOADING_ALL_USER_LIST = 'FAILED_LOADING_ALL_USER_LIST';